# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/Peripheral_Interface_lab6/MIPSfpga_keyboard/MIPSfpga_axi4.srcs/sources_1/bd/MIPSfpga_system/ip/MIPSfpga_system_blk_mem_gen_1_0/MIPSfpga_system_blk_mem_gen_1_0.xci
# IP: The module: 'MIPSfpga_system_blk_mem_gen_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Peripheral_Interface_lab6/MIPSfpga_keyboard/MIPSfpga_axi4.srcs/sources_1/bd/MIPSfpga_system/ip/MIPSfpga_system_blk_mem_gen_1_0/MIPSfpga_system_blk_mem_gen_1_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'MIPSfpga_system_blk_mem_gen_1_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: E:/Peripheral_Interface_lab6/MIPSfpga_keyboard/MIPSfpga_axi4.srcs/sources_1/bd/MIPSfpga_system/ip/MIPSfpga_system_blk_mem_gen_1_0/MIPSfpga_system_blk_mem_gen_1_0.xci
# IP: The module: 'MIPSfpga_system_blk_mem_gen_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Peripheral_Interface_lab6/MIPSfpga_keyboard/MIPSfpga_axi4.srcs/sources_1/bd/MIPSfpga_system/ip/MIPSfpga_system_blk_mem_gen_1_0/MIPSfpga_system_blk_mem_gen_1_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'MIPSfpga_system_blk_mem_gen_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
