# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir E:/Peripheral_Interface_lab6/MIPSfpga_keyboard/MIPSfpga_axi4.cache/wt [current_project]
set_property parent.project_path E:/Peripheral_Interface_lab6/MIPSfpga_keyboard/MIPSfpga_axi4.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths e:/Peripheral_Interface_lab6/ip_repo [current_project]
add_files E:/Peripheral_Interface_lab6/ram_init.coe
add_files -quiet E:/Peripheral_Interface_lab6/MIPSfpga_keyboard/MIPSfpga_axi4.runs/MIPSfpga_system_synth_1/MIPSfpga_system.dcp
set_property used_in_implementation false [get_files E:/Peripheral_Interface_lab6/MIPSfpga_keyboard/MIPSfpga_axi4.runs/MIPSfpga_system_synth_1/MIPSfpga_system.dcp]
read_verilog -library xil_defaultlib E:/Peripheral_Interface_lab6/MIPSfpga_keyboard/MIPSfpga_axi4.srcs/sources_1/bd/MIPSfpga_system/hdl/MIPSfpga_system_wrapper.v
read_xdc E:/Peripheral_Interface_lab6/MIPSfpga_keyboard/MIPSfpga_axi4.srcs/constrs_1/imports/MIPSfpga_Peripheral_2017/MIPSfpga_axi4.xdc
set_property used_in_implementation false [get_files E:/Peripheral_Interface_lab6/MIPSfpga_keyboard/MIPSfpga_axi4.srcs/constrs_1/imports/MIPSfpga_Peripheral_2017/MIPSfpga_axi4.xdc]

synth_design -top MIPSfpga_system_wrapper -part xc7a100tcsg324-1
write_checkpoint -noxdef MIPSfpga_system_wrapper.dcp
catch { report_utilization -file MIPSfpga_system_wrapper_utilization_synth.rpt -pb MIPSfpga_system_wrapper_utilization_synth.pb }
