import random
import re
import sys

import serial
from PyQt5 import QtCore, QtWidgets

from Ui_keyinput import Ui_GUIMainWindow


class App(QtWidgets.QWidget, Ui_GUIMainWindow):

    def __init__(self, parent=None):
        # initialization of the superclass
        super(App, self).__init__()
        # setup the GUI --> function generated by pyuic4
        self.setupUi(self)
        # connect the signals with the slots
        self.verticalSlider_period.valueChanged.connect(self.setPeriod)
        self.timer = QtCore.QTimer()
        self.timer.timeout.connect(self.read_data)
        self.serial = serial.Serial('COM6', 115200, timeout=1)
        if False == self.serial.isOpen():
            print("faild to open serial port!\n")
        else:
            self.timer.start(100)
        self.data = list()

    def read_data(self):
        text = self.serial.read_all()
        if (len(text) > 0):
            print(text.decode())
            self.textEdit_text.insertPlainText(text.decode())

    def setPeriod(self):
        period = self.verticalSlider_period.value()
        self.serial.write(period)


if __name__ == '__main__':
    app = QtWidgets.QApplication(sys.argv)
    ex = App()
    ex.show()
    sys.exit(app.exec_())
