import random
import re
import sys

import serial
from PyQt5 import QtCore, QtWidgets

from Ui_keyinput import Ui_GUIMainWindow


class App(QtWidgets.QWidget, Ui_GUIMainWindow):

    def __init__(self, parent=None):
        # initialization of the superclass
        super(App, self).__init__()
        # setup the GUI --> function generated by pyuic4
        self.setupUi(self)
        # connect the signals with the slots
        
        self.pushButton_setfaultqueue.clicked.connect(self.setFaultQueue)
        self.timer = QtCore.QTimer()
        self.timer.timeout.connect(self.read_data)
        self.serial = serial.Serial('COM6', 115200, timeout=1)
        if False == self.serial.isOpen():
            print("faild to open serial port!\n")
        else:
            self.timer.start(100)
        self.data = list()


    def read_data(self):
        text = self.serial.read_all()
        print(text)
        #self.textEdit_log.clear()
        self.textEdit_text.insertPlainText(text.decode())

        temp = re.findall(r"keycode: (?P<temp>[0-9]*\n\r)", text.decode())

        for t in temp:
            print(float(t))
            if len(self.data) >= 60:
                del self.data[0]
            self.data.append(float(t)/16)
        self.mplfigure.canvas.ax.clear()
        self.mplfigure.canvas.ax.plot(self.data, '*-')
        self.mplfigure.canvas.draw()

    def setResolution(self):
        self.serial.write('r'.encode())
        if self.radioButton_13bits.isChecked():
            self.serial.write('1'.encode())
        elif self.radioButton_16bits.isChecked():
            self.serial.write('2'.encode())
        else:
            print("error in setResolution")


if __name__ == '__main__':
    app = QtWidgets.QApplication(sys.argv)
    ex = App()
    ex.show()
    sys.exit(app.exec_())
