# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\Peripheral_Interface_lab6_Keyboard_C\lab5gui\keyinput.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_GUIMainWindow(object):
    def setupUi(self, GUIMainWindow):
        GUIMainWindow.setObjectName("GUIMainWindow")
        GUIMainWindow.resize(481, 258)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(GUIMainWindow.sizePolicy().hasHeightForWidth())
        GUIMainWindow.setSizePolicy(sizePolicy)
        GUIMainWindow.setFocusPolicy(QtCore.Qt.TabFocus)
        self.gridLayout = QtWidgets.QGridLayout(GUIMainWindow)
        self.gridLayout.setObjectName("gridLayout")
        self.label_4 = QtWidgets.QLabel(GUIMainWindow)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 7, 10, 1, 1)
        self.label_3 = QtWidgets.QLabel(GUIMainWindow)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 8, 10, 1, 1)
        self.label_8 = QtWidgets.QLabel(GUIMainWindow)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 12, 10, 1, 1)
        self.label_9 = QtWidgets.QLabel(GUIMainWindow)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 13, 10, 1, 1)
        self.label_12 = QtWidgets.QLabel(GUIMainWindow)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 16, 10, 1, 1)
        self.label_11 = QtWidgets.QLabel(GUIMainWindow)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 15, 10, 1, 1)
        self.label_10 = QtWidgets.QLabel(GUIMainWindow)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 14, 10, 1, 1)
        self.label = QtWidgets.QLabel(GUIMainWindow)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 7, 8, 10, 1)
        self.label_6 = QtWidgets.QLabel(GUIMainWindow)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 10, 10, 1, 1)
        self.label_7 = QtWidgets.QLabel(GUIMainWindow)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 11, 10, 1, 1)
        self.label_5 = QtWidgets.QLabel(GUIMainWindow)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 9, 10, 1, 1)
        self.label_2 = QtWidgets.QLabel(GUIMainWindow)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 7, 11, 1, 1)
        self.verticalSlider_period = QtWidgets.QSlider(GUIMainWindow)
        self.verticalSlider_period.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.verticalSlider_period.setAutoFillBackground(True)
        self.verticalSlider_period.setMinimum(0)
        self.verticalSlider_period.setMaximum(9)
        self.verticalSlider_period.setPageStep(1)
        self.verticalSlider_period.setProperty("value", 5)
        self.verticalSlider_period.setSliderPosition(5)
        self.verticalSlider_period.setTracking(False)
        self.verticalSlider_period.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_period.setInvertedAppearance(False)
        self.verticalSlider_period.setInvertedControls(True)
        self.verticalSlider_period.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.verticalSlider_period.setTickInterval(1)
        self.verticalSlider_period.setObjectName("verticalSlider_period")
        self.gridLayout.addWidget(self.verticalSlider_period, 7, 9, 10, 1)
        self.textEdit_text = QtWidgets.QPlainTextEdit(GUIMainWindow)
        self.textEdit_text.setReadOnly(True)
        self.textEdit_text.setObjectName("textEdit_text")
        self.gridLayout.addWidget(self.textEdit_text, 8, 11, 8, 1)

        self.retranslateUi(GUIMainWindow)
        QtCore.QMetaObject.connectSlotsByName(GUIMainWindow)

    def retranslateUi(self, GUIMainWindow):
        _translate = QtCore.QCoreApplication.translate
        GUIMainWindow.setWindowTitle(_translate("GUIMainWindow", "接口综合实验GUI"))
        self.label_4.setText(_translate("GUIMainWindow", "9"))
        self.label_3.setText(_translate("GUIMainWindow", "8"))
        self.label_8.setText(_translate("GUIMainWindow", "4"))
        self.label_9.setText(_translate("GUIMainWindow", "3"))
        self.label_12.setText(_translate("GUIMainWindow", "0"))
        self.label_11.setText(_translate("GUIMainWindow", "1"))
        self.label_10.setText(_translate("GUIMainWindow", "2"))
        self.label.setText(_translate("GUIMainWindow", "LED亮度调节"))
        self.label_6.setText(_translate("GUIMainWindow", "6"))
        self.label_7.setText(_translate("GUIMainWindow", "5"))
        self.label_5.setText(_translate("GUIMainWindow", "7"))
        self.label_2.setText(_translate("GUIMainWindow", "键盘输入内容"))
        self.verticalSlider_period.setStatusTip(_translate("GUIMainWindow", "水电费"))
        self.verticalSlider_period.setWhatsThis(_translate("GUIMainWindow", "水电费发送"))

