# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir E:/Peripheral_Interface_lab/ip_repo/edit_PS2Receiver_v1_0.cache/wt [current_project]
set_property parent.project_path E:/Peripheral_Interface_lab/ip_repo/edit_PS2Receiver_v1_0.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths {
  e:/Peripheral_Interface_lab/ip_repo/PS2Receiver_1.0
  e:/Peripheral_Interface_lab/ip_repo/keyboard_1.0
} [current_project]
read_verilog -library xil_defaultlib {
  E:/Peripheral_Interface_lab/ip_repo/PS2Receiver_1.0/hdl/debouncer.v
  E:/Peripheral_Interface_lab/ip_repo/ps2receiver_1.0/hdl/PS2Receiver_v1_0_S00_AXI.v
  E:/Peripheral_Interface_lab/ip_repo/edit_PS2Receiver_v1_0.srcs/sources_1/imports/hdl/PS2Receiver.v
  E:/Peripheral_Interface_lab/ip_repo/ps2receiver_1.0/hdl/PS2Receiver_v1_0.v
}
read_xdc E:/Peripheral_Interface_lab/ip_repo/PS2Receiver_1.0/src/Nexys4DDR_Master.xdc
set_property used_in_implementation false [get_files E:/Peripheral_Interface_lab/ip_repo/PS2Receiver_1.0/src/Nexys4DDR_Master.xdc]

synth_design -top PS2Receiver_v1_0 -part xc7a100tcsg324-1
write_checkpoint -noxdef PS2Receiver_v1_0.dcp
catch { report_utilization -file PS2Receiver_v1_0_utilization_synth.rpt -pb PS2Receiver_v1_0_utilization_synth.pb }
