# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {HDL-1065} -limit 10000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir E:/Peripheral_Interface_lab/ip_repo/Video_Out_to_VGA_12bits/Video_Out_to_VGA_12bits.cache/wt [current_project]
set_property parent.project_path E:/Peripheral_Interface_lab/ip_repo/Video_Out_to_VGA_12bits/Video_Out_to_VGA_12bits.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib E:/Peripheral_Interface_lab/ip_repo/Video_Out_to_VGA_12bits/Video_Out_to_VGA_12bits.srcs/sources_1/new/Video_Out_to_VGA.v
synth_design -top Video_Out_to_VGA -part xc7a100tcsg324-1
write_checkpoint -noxdef Video_Out_to_VGA.dcp
catch { report_utilization -file Video_Out_to_VGA_utilization_synth.rpt -pb Video_Out_to_VGA_utilization_synth.pb }
